2025-05-29 12:50:07,503 [WARNING] Failed to connect 
2025-05-29 12:50:07,610 [INFO] Waiting for connection
2025-05-29 12:50:12,620 [ERROR] Timeout while waiting for connection. Reconnecting
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Andraž\Desktop\huawei_sun2000_control\.venv\Lib\site-packages\huawei_solar\huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2025-05-29 13:02:55,317 [INFO] Waiting for connection
2025-05-29 13:02:56,720 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 13:02:56,722 [INFO] Backing off _do_read(...) for 1.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 13:02:57,728 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 13:02:57,730 [INFO] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 13:02:59,742 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 13:02:59,744 [INFO] Backing off _do_read(...) for 4.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 13:03:03,750 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 13:03:03,751 [INFO] Backing off _do_read(...) for 8.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 13:03:11,756 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 13:03:11,757 [INFO] Backing off _do_read(...) for 16.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 13:03:27,763 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 13:03:27,764 [ERROR] Giving up _do_read(...) after 6 tries (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:03:01,361 [INFO] Waiting for connection
2025-05-29 15:03:02,683 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:03:02,686 [INFO] Backing off _do_read(...) for 1.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:03:03,692 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:03:03,693 [INFO] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:03:05,694 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:03:05,696 [INFO] Backing off _do_read(...) for 4.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:03:09,696 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:03:09,697 [INFO] Backing off _do_read(...) for 8.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:03:17,712 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:03:17,713 [INFO] Backing off _do_read(...) for 16.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:03:33,726 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:03:33,728 [ERROR] Giving up _do_read(...) after 6 tries (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:04:02,795 [INFO] Waiting for connection
2025-05-29 15:04:04,180 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:04:04,182 [INFO] Backing off _do_read(...) for 1.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:04:05,190 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:04:05,191 [INFO] Backing off _do_read(...) for 2.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:04:07,205 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:04:07,207 [INFO] Backing off _do_read(...) for 4.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:04:11,218 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:04:11,219 [INFO] Backing off _do_read(...) for 8.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:04:19,221 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:04:19,222 [INFO] Backing off _do_read(...) for 16.0s (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:04:35,239 [ERROR] Modbus client is not connected to the inverter
NoneType: None
2025-05-29 15:04:35,240 [ERROR] Giving up _do_read(...) after 6 tries (huawei_solar.exceptions.ConnectionInterruptedException: Modbus client is not connected to the inverter)
2025-05-29 15:11:09,295 [INFO] Waiting for connection
2025-05-29 15:11:13,311 [INFO] Logged in as installer; waiting 5s for inverter to stabilize...
2025-05-29 15:11:18,342 [INFO] [READ] Target SoC (%) @ N/A = 0.0
2025-05-29 15:11:18,418 [INFO] [READ] Forced Period (min) @ N/A = 0
2025-05-29 15:11:18,477 [INFO] [READ] Max Charge Power (W) @ N/A = 0
2025-05-29 15:11:18,668 [INFO] [READ] Max Discharge Power (W) @ N/A = 0
2025-05-29 15:11:18,732 [INFO] [READ] Mode (0=Idle,1=Charge,2=Discharge) @ N/A = Stop
2025-05-29 15:11:18,734 [INFO] Bridge stopped successfully.
2025-05-29 15:14:16,463 [INFO] Waiting for connection
2025-05-29 15:14:20,325 [INFO] Logged in as installer; waiting 5s for inverter to stabilize...
2025-05-29 15:14:25,360 [INFO] [READ] Target SoC (%) @ N/A = 0.0
2025-05-29 15:14:25,431 [INFO] [READ] Forced Period (min) @ N/A = 0
2025-05-29 15:14:25,509 [INFO] [READ] Max Charge Power (W) @ N/A = 0
2025-05-29 15:14:25,681 [INFO] [READ] Max Discharge Power (W) @ N/A = 0
2025-05-29 15:14:25,742 [INFO] [READ] Mode (0=Idle,1=Charge,2=Discharge) @ N/A = Stop
2025-05-29 15:14:25,743 [INFO] Bridge stopped successfully.
2025-05-29 15:19:11,089 [WARNING] Failed to connect 
2025-05-29 15:19:11,199 [INFO] Waiting for connection
2025-05-29 15:19:16,218 [ERROR] Timeout while waiting for connection. Reconnecting
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Andraž\Desktop\huawei_sun2000_control\.venv\Lib\site-packages\huawei_solar\huawei_solar.py", line 141, in _communication_lock
    await asyncio.wait_for(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
2025-05-29 15:19:36,206 [INFO] Waiting for connection
2025-05-29 15:19:39,982 [INFO] Logged in as installer; waiting 5s for inverter to stabilize...
2025-05-29 15:19:45,031 [INFO] [READ] Target SoC (%) @ N/A = 459
2025-05-29 15:19:45,097 [INFO] [READ] Forced Period (min) @ N/A = 0
2025-05-29 15:19:45,162 [INFO] [READ] Max Charge Power (W) @ N/A = 0
2025-05-29 15:19:45,233 [INFO] [READ] Max Discharge Power (W) @ N/A = 0
2025-05-29 15:19:45,302 [INFO] [READ] Mode (0=Idle,1=Charge,2=Discharge) @ N/A = Stop
2025-05-29 15:19:45,304 [INFO] Bridge stopped successfully.
2025-05-29 15:45:17,766 [INFO] Waiting for connection
2025-05-29 15:45:21,732 [INFO] Logged in as installer; waiting 5s for inverter to stabilize...
2025-05-29 15:45:26,748 [INFO] [READ] Target SoC (%) @ N/A = -19
2025-05-29 15:45:26,812 [INFO] [READ] Forced Period (min) @ N/A = 0
2025-05-29 15:45:26,874 [INFO] [READ] Max Charge Power (W) @ N/A = 0
2025-05-29 15:45:26,938 [INFO] [READ] Max Discharge Power (W) @ N/A = 0
2025-05-29 15:45:27,014 [INFO] [READ] Mode (0=Idle,1=Charge,2=Discharge) @ N/A = Stop
2025-05-29 15:45:27,016 [INFO] Bridge stopped successfully.
2025-05-29 15:48:45,113 [INFO] Waiting for connection
2025-05-29 15:48:48,736 [INFO] Logged in as installer; waiting 5s for inverter to stabilize...
2025-05-29 15:48:53,805 [INFO] [READ] Target SoC (%) @ N/A = 0.0
2025-05-29 15:48:53,870 [INFO] [READ] Forced Period (min) @ N/A = 0
2025-05-29 15:48:53,931 [INFO] [READ] Max Charge Power (W) @ N/A = 0
2025-05-29 15:48:54,005 [INFO] [READ] Max Discharge Power (W) @ N/A = 0
2025-05-29 15:48:54,080 [INFO] [READ] Mode (0=Idle,1=Charge,2=Discharge) @ N/A = Stop
2025-05-29 15:48:54,082 [INFO] Bridge stopped successfully.
2025-05-29 15:59:30,789 [INFO] Waiting for connection
2025-05-29 15:59:34,326 [INFO] Logged in as installer; waiting 5s for inverter to stabilize...
2025-05-29 16:04:14,132 [INFO] Waiting for connection
2025-05-29 16:04:18,193 [INFO] Logged in as installer; waiting 5s for inverter to stabilize...
2025-05-29 16:04:23,200 [INFO] Bridge stopped successfully.
2025-05-29 16:10:43,988 [INFO] Waiting for connection
2025-05-29 16:10:47,505 [INFO] Logged in as installer on slave 0; waiting 5s…
2025-05-29 16:10:52,616 [INFO] Waiting for connection
2025-05-29 16:11:34,038 [ERROR] No response received after 3 retries, continue with next request
2025-05-30 10:34:41,477 [INFO] Waiting for connection
2025-05-30 10:34:45,228 [INFO] Logged in as installer on slave 0; waiting 5s…
2025-05-30 10:34:50,421 [INFO] Waiting for connection
2025-05-30 10:35:31,851 [ERROR] No response received after 3 retries, continue with next request
2025-05-30 10:41:09,647 [INFO] Waiting for connection
2025-05-30 10:41:13,538 [INFO] Logged in as installer on slave 0; waiting 5s…
2025-05-30 10:41:18,611 [INFO] Connection closed.
